In [16]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in d:\softwareproject\.venv\lib\site-packages (1.2.1)

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import torch
import pandas as pd

In [18]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [19]:
from dotenv import load_dotenv
load_dotenv()
import os
access_token = os.getenv('HF_TOKEN')

In [20]:
model_name = "asjc-classification/scibert_multilabel_asjc_classifier"

In [21]:
tokernizer =  AutoTokenizer.from_pretrained(model_name,token=access_token)
model = AutoModelForCausalLM.from_pretrained(model_name,token=access_token)

If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

This checkpoint seem corrupted. The tied weights mapping for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are absent from the checkpoint, and we could not find another related tied weight for those keys
BertLMHeadModel LOAD REPORT from: asjc-classification/scibert_multilabel_asjc_classifier
Key                                        | Status     |
-------------------------------------------+------------+-
classifier.bias                            | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
classifier.weight                          | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.dense.weight     | MISSING    |
cls.predictions.transform.LayerNorm.bias   | MISSING    |
cls.predictions.decoder.bias               | MISSING    |
cls.predictions.transform.dense.bias       | MISSING    |
cls.predictions.bias                       | MISSING    |
cls.predictions.transform.LayerNorm.weight | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [22]:
tokernizer.save_pretrained(f"/filed_classification_models_for_software_project/tokenizer/{model_name}")
model.save_pretrained(f"/filed_classification_models_for_software_project/model/{model_name}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
# Load merged file
df = pd.read_csv('D:/SoftwareProject/3_fileds_using_api/3filds/final_dataset.csv')

# Combine Title and Abstract for the model to read
df['input_text'] = df['title'].fillna('') + ". " + df['abstract'].fillna('')

print(f"Loaded {len(df)} rows of research metadata.")

Loaded 24015 rows of research metadata.

In [24]:
df.head()

,title,abstract,field_1_na,field_1_co,field_2_na,field_2_co,field_3_na,field_3_co,source_file,input_text
0,Discontinuities between maternity and child an...,BackgroundContinuity in the context of healthc...,"Public Health, Environmental and Occupational ...",45.00%,Health (social science),35.00%,Nursing (miscellaneous),20.00%,output2.csv,Discontinuities between maternity and child an...
1,An interactive decision-making framework (i-DM...,Background Low numbers of women in Queensland ...,Health Policy,45.00%,"Public Health, Environmental and Occupational ...",35.00%,Ecology,20.00%,output2.csv,An interactive decision-making framework (i-DM...
2,Midwifery-led care can lower caesarean section...,INTRODUCTION Midwifery-led care is recognised ...,Ecology,85.00%,"Public Health, Environmental and Occupational ...",10.00%,Maternity and Midwifery,5.00%,output2.csv,Midwifery-led care can lower caesarean section...
3,The association between midwifery staffing lev...,Background Women have consistently reported lo...,Nursing (miscellaneous),70.00%,"Public Health, Environmental and Occupational ...",20.00%,Health Policy,10.00%,output2.csv,The association between midwifery staffing lev...
4,Competencies for respectful maternity care: Id...,"BACKGROUND\nA respectful, person-centered phil...",Nursing (miscellaneous),70.00%,"Public Health, Environmental and Occupational ...",20.00%,Ecology,10.00%,output2.csv,Competencies for respectful maternity care: Id...

In [25]:
df = df.drop('source_file', axis=1)

In [26]:
df.head()

,title,abstract,field_1_na,field_1_co,field_2_na,field_2_co,field_3_na,field_3_co,input_text
0,Discontinuities between maternity and child an...,BackgroundContinuity in the context of healthc...,"Public Health, Environmental and Occupational ...",45.00%,Health (social science),35.00%,Nursing (miscellaneous),20.00%,Discontinuities between maternity and child an...
1,An interactive decision-making framework (i-DM...,Background Low numbers of women in Queensland ...,Health Policy,45.00%,"Public Health, Environmental and Occupational ...",35.00%,Ecology,20.00%,An interactive decision-making framework (i-DM...
2,Midwifery-led care can lower caesarean section...,INTRODUCTION Midwifery-led care is recognised ...,Ecology,85.00%,"Public Health, Environmental and Occupational ...",10.00%,Maternity and Midwifery,5.00%,Midwifery-led care can lower caesarean section...
3,The association between midwifery staffing lev...,Background Women have consistently reported lo...,Nursing (miscellaneous),70.00%,"Public Health, Environmental and Occupational ...",20.00%,Health Policy,10.00%,The association between midwifery staffing lev...
4,Competencies for respectful maternity care: Id...,"BACKGROUND\nA respectful, person-centered phil...",Nursing (miscellaneous),70.00%,"Public Health, Environmental and Occupational ...",20.00%,Ecology,10.00%,Competencies for respectful maternity care: Id...

In [27]:
total_unique = pd.concat([df['field_1_na'], df['field_2_na'], df['field_3_na']]).nunique()
print(f"Total unique research fields across all columns: {total_unique}")

Total unique research fields across all columns: 431

In [28]:
# Combine the three field columns into one long Series
all_fields_combined = pd.concat([df['field_1_na'], df['field_2_na'], df['field_3_na']])

# Get unique values and convert to a sorted list for consistency
unique_fields_list = sorted(all_fields_combined.dropna().unique().tolist())


print(f"Total Unique Fields: {len(unique_fields_list)}")

Total Unique Fields: 431

In [29]:
print(unique_fields_list)

['Accounting', 'Acoustics and Ultrasonics', 'Aerospace Engineering', 'Aging', 'Agricultural and Biological Sciences (miscellaneous)', 'Agronomy and Crop Science', 'Algebra and Number Theory', 'Algebraic Topology,', 'Allergy,', 'Analysis', 'Analytical Chemistry', 'Anatomy', 'Anesthesiology and Pain Medicine', 'Animal Science and Zoology', 'Anthropology', 'Applied Mathematics', 'Applied Psychology', 'Aquaculture,', 'Aquatic Science', 'Archeology', 'Archeology (arts and humanities)', 'Architecture', 'Artificial Intelligence', 'Arts and Humanities (miscellaneous)', 'Assessment and Diagnosis', 'Astronomy and Astrophysics', 'Astrophysics and Cosmology,', 'Astrophysics of Galaxies,', 'Astrophysics,', 'Atmospheric Science', 'Atomic and Molecular Physics,', 'Atomic and Molecular Physics, and Optics', 'Audiology,', 'Automotive Engineering', 'Behavioral Neuroscience', 'Bibliometrics,', 'Biochemistry', 'Biochemistry, Genetics and Molecular Biology (miscellaneous)', 'Bioengineering', 'Bioethics,', 'Bioinformatics,', 'Biology (miscellaneous),', 'Biology,', 'Biomaterials', 'Biomechanics,', 'Biomedical Engineering', 'Biophysics', 'Biotechnology', 'Building and Construction', 'Business and International Management', 'Business, Management and Accounting ', 'Cancer Research', 'Cardiology and Cardiovascular Medicine', 'Catalysis', 'Cell Biology', 'Cellular and Molecular Neuroscience', 'Ceramics and Composites', 'Chemical Engineering', 'Chemical Health and Safety', 'Chemical Physics,', 'Chemistry (miscellaneous)', 'Chemistry,', 'Chiropractics', 'Civil and Structural Engineering', 'Classics', 'Clinical Psychology', 'Coaching,', 'Cognitive Neuroscience', 'Cognitive Science,', 'Colloid and Surface Chemistry', 'Communication', 'Community and Home Care', 'Complementary and Alternative Medicine', 'Complementary and Manual Therapy', 'Computational Biology,', 'Computational Chemistry,', 'Computational Fluid Dynamics,', 'Computational Mathematics', 'Computational Mechanics', 'Computational Neuroscience,', 'Computational Theory and Mathematics', 'Computer Graphics and Computer-Aided Design', 'Computer Hardware,', 'Computer Networks and Communications', 'Computer Science', 'Computer Vision and Pattern Recognition', 'Computer-Aided Design,', 'Computers in Earth Sciences', 'Condensed Matter Physics', 'Conservation', 'Control and Optimization', 'Control and Systems Engineering', 'Corrosion,', 'Criminology and Penology,', 'Critical Care Nursing', 'Critical Care and Intensive Care Medicine', 'Crystallography and Structural Chemistry,', 'Crystallography,', 'Cultural Studies', 'Curriculum and Instruction,', 'Curriculum and Pedagogy,', 'Curriculum,', 'Decision Sciences (miscellaneous)', 'Decision Sciences,', 'Demography', 'Dental Assisting', 'Dental Hygiene', 'Dental Materials,', 'Dentistry (miscellaneous)', 'Dermatology', 'Development', 'Developmental Biology', 'Developmental Neuroscience', 'Developmental and Educational Psychology', 'Discrete Mathematics and Combinatorics', 'Drug Discovery', 'Earth and Planetary Sciences ', 'Earth and Planetary Sciences,', 'Earth-Surface Processes', 'Ecological Modeling', 'Ecology', 'Ecology, Evolution, Behavior and Systematics', 'Economic Geology', 'Economics and Econometrics', 'Economics,', 'Economics, Econometrics and Finance', 'Education', 'Electrical and Electronic Engineering', 'Electrochemistry', 'Electronic, Optical and Magnetic Materials', 'Embryology', 'Emergency Medical Services', 'Emergency Medicine', 'Emergency Nursing', 'Endocrinology', 'Energy', 'Engineering (miscellaneous)', 'Engineering,', 'Entomology,', 'Environmental Chemistry', 'Environmental Engineering,', 'Environmental Science (miscellaneous)', 'Environmental Science,', 'Epidemiology', 'Equine', 'Ethics,', 'Evolution, Behavior and Systematics,', 'Evolutionary Biology,', 'Evolutionary Psychology,', 'Experimental and Cognitive Psychology', 'Family Practice', 'Filtration and Separation', 'Finance', 'Fluid Flow and Transfer Processes', 'Food Animals', 'Food Safety,', 'Food Science', 'Forensic Medicine,', 'Forensic Science,', 'Forestry', 'Fuel Technology', 'Gastroenterology', 'Gender Studies', 'General Agricultural and Biological Sciences', 'General Arts and Humanities', 'General Biochemistry, Genetics and Molecular Biology', 'General Business, Management and Accounting', 'General Chemical Engineering', 'General Chemistry', 'General Computer Science', 'General Decision Sciences', 'General Dentistry', 'General Earth and Planetary Sciences', 'General Economics,', 'General Economics, Econometrics and Finance', 'General Energy', 'General Engineering', 'General Environmental Science', 'General Health Professions', 'General Immunology and Microbiology', 'General Materials Science', 'General Mathematics', 'General Medicine', 'General Neuroscience', 'General Nursing', 'General Pharmacology, Toxicology and Pharmaceutics', 'General Physics and Astronomy', 'General Psychology', 'General Relativity and Cosmology,', 'General Relativity and Gravitation,', 'General Relativity and Quantum Cosmology,', 'General Social Sciences', 'General Veterinary', 'Genetics', 'Geochemistry and Petrology', 'Geology', 'Geometry and Topology', 'Geophysics', 'Geriatrics and Gerontology', 'Global and Planetary Change', 'Graph Theory,', 'Green chemistry,', 'Hardware and Architecture', 'Health (social science)', 'Health Informatics', 'Health Information Management', 'Health Policy', 'Health Professions (miscellaneous)', 'Health Psychology,', 'Health, Toxicology and Mutagenesis', 'Heat Transfer,', 'Hematology', 'Hepatology', 'Histology', 'History', 'Horticulture', 'Human Biology,', 'Human Factors and Ergonomics', 'Human Rights,', 'Human-Animal Interaction,', 'Human-Computer Interaction', 'Immunology', 'Immunology and Microbiology ', 'Industrial Relations', 'Industrial and Manufacturing Engineering', 'Infectious Diseases', 'Information Systems', 'Inorganic Chemistry', 'Insect Science', 'Instrumentation', 'Internal Medicine', 'Issues, Ethics and Legal Aspects,', 'Language and Linguistics', 'Law', 'Leadership and Management', 'Library and Information Sciences', 'Life-span and Life-course Studies', 'Linguistics and Language', 'Literature and Literary Theory', 'Logic', 'Magnetism,', 'Management Information Systems', 'Management Science and Operations Research', 'Management of Technology and Innovation', 'Management,', 'Management, Monitoring, Policy and Law', 'Marketing', 'Materials Chemistry', 'Materials Science', 'Maternity and Midwifery', 'Mathematical Physics', 'Mathematical and Theoretical Biology,', 'Mathematics (miscellaneous)', 'Mathematics,', 'Mechanical Engineering', 'Mechanics of Materials', 'Media Technology', 'Medical Ethics,', 'Medical Informatics,', 'Medical Laboratory Technology', 'Medical Sciences,', 'Medical Terminology', 'Medical and Surgical Nursing', 'Medicinal Chemistry,', 'Medicine (miscellaneous)', 'Metabolic Engineering,', 'Metabolomics,', 'Metals and Alloys', 'Microbiology', 'Mining and Mineral Processing,', 'Modeling and Simulation', 'Molecular Biology', 'Molecular Medicine', 'Multidisciplinary', 'Museology', 'Music', 'Mycology,', 'Nanomedicine,', 'Nanoscience and Nanotechnology,', 'Nanotechnology and Nanomaterials,', 'Nanotechnology and Nanomedicine,', 'Nanotechnology,', 'Nephrology', 'Neurology (clinical)', 'Neuroscience (miscellaneous)', 'Neuroscience,', 'Neurosciences,', 'Nonlinear dynamics,', 'Nuclear Physics,', 'Number Theory,', 'Nursing (miscellaneous)', 'Nursing,', 'Nutrition and Dietetics', 'Occupational Therapy', 'Ocean Engineering', 'Oceanography', 'Oncology', 'Ophthalmology', 'Optical and Magnetic Materials,', 'Optics and Photonics,', 'Optics,', 'Optometry', 'Organic Chemistry', 'Organizational Behavior and Human Resource Management', 'Orthodontics', 'Orthopedics and Sports Medicine', 'Otorhinolaryngology', 'Pain Management,', 'Paleontology', 'Parasitology', 'Pathology and Forensic Medicine', 'Pediatrics', 'Pediatrics, Perinatology and Child Health', 'Performing Arts,', 'Periodontics', 'Pharmaceutical Science', 'Pharmacology', 'Pharmacology (medical)', 'Pharmacology (nursing)', 'Pharmacology, Toxicology and Pharmaceutics (miscellaneous)', 'Pharmacy', 'Philosophy', 'Photodynamic Therapy,', 'Physical and Theoretical Chemistry', 'Physics and Astronomy (miscellaneous)', 'Physics and Astronomy,', 'Physiology', 'Plant Science', 'Plasma and Beam Physics,', 'Podiatry', 'Political Science and International Relations', 'Pollution', 'Polymer Science,', 'Polymer and Plastics,', 'Polymers and Plastics', 'Population Biology,', 'Precision Medicine,', 'Probability and Uncertainty,', 'Probability,', 'Process Chemistry and Technology', 'Prosthodontics,', 'Proteomics,', 'Psychiatric Mental Health', 'Psychiatry and Mental Health', 'Psychology (miscellaneous)', 'Psychology,', 'Public Administration', 'Public Health, Environmental and Occupational Health', 'Publishing,', 'Pulmonary and Respiratory Medicine', 'Quantum Computing,', 'Quantum Physics,', 'Radiation', 'Regenerative Medicine,', 'Rehabilitation', 'Reliability,', 'Religious Studies', 'Remote Sensing,', 'Representation Theory,', 'Reproductive Medicine', 'Research and Theory', 'Rheumatology', 'Robotics and Automation,', 'Robotics,', 'Safety Research', 'Safety, Risk, Reliability and Quality', 'Science (miscellaneous),', 'Science Pedagogy,', 'Science and Society,', 'Science and Technology Studies,', 'Scientometrics,', 'Security and Privacy,', 'Security and Risk,', 'Sensory Systems', 'Signal Processing', 'Small Animals', 'Social Psychology', 'Social Sciences (miscellaneous)', 'Social Sciences,', 'Sociology and Political Science', 'Soft Materials,', 'Soft Matter,', 'Software', 'Soil Science', 'Space and Planetary Science', 'Spectroscopy', 'Speech and Hearing', 'Sports Medicine,', 'Sports Science,', 'Statistical Mechanics,', 'Statistical and Nonlinear Physics', 'Statistics and Probability', 'Statistics,', 'Statistics, Probability and Uncertainty', 'Strategic and Management,', 'Strategy and Management', 'Structural Biology', 'Superconductivity,', 'Surfaces and Interfaces', 'Surfaces, Coatings and Films', 'Surgery', 'Sustainability and the Environment,', 'Synthetic Biology,', 'Systems Biology,', 'Systems Engineering,', 'Theology,', 'Theoretical Biology,', 'Theoretical Chemistry,', 'Theoretical Physics,', 'Theoretical Psychology,', 'Thermal Science,', 'Thermal and Statistical Physics,', 'Thermodynamics,', 'Topology,', 'Tourism, Leisure and Hospitality Management', 'Toxicology', 'Transfusion,', 'Translation and Interpretation,', 'Translation process research,', 'Translation,', 'Transplantation', 'Transportation', 'Urban Studies', 'Urology', 'Veterinary (miscellaneous)', 'Veterinary,', 'Virology', 'Visual Arts and Performing Arts', 'Visualization,', 'Waste Management and Disposal', 'Water Science and Technology']

In [40]:
#Combine all three field columns to get the total
# count for every field
all_fields = pd.concat([df['field_1_na']])

#Calculate the frequency of each field
field_counts = all_fields.value_counts()

#Filter the field_counts for those less than 20
low_frequency_fields = field_counts[field_counts < 20]

#Get just the names as a list
low_frequency_names = low_frequency_fields.index.tolist()


print(f"Total fields with < 20 occurrences: {len(low_frequency_names)}")
print("--- List of Names ---")
for name in low_frequency_names:
    print(name)

print(low_frequency_fields)

Total fields with < 20 occurrences: 133
--- List of Names ---
Mathematical Physics
General Social Sciences
Water Science and Technology
Literature and Literary Theory
Computational Biology,
Waste Management and Disposal
Gender Studies
Conservation
Computer Graphics and Computer-Aided Design
Automotive Engineering
Forestry
Insect Science
Building and Construction
Computational Mechanics
Medical Laboratory Technology
Structural Biology
Software
Geology
General Energy
Nursing,
Molecular Biology
Geophysics
Biochemistry, Genetics and Molecular Biology (miscellaneous)
Bioinformatics,
General Dentistry
Robotics,
Logic
General Earth and Planetary Sciences
Developmental Neuroscience
Management Information Systems
Behavioral Neuroscience
Geometry and Topology
Space and Planetary Science
Arts and Humanities (miscellaneous)
Theoretical Physics,
Colloid and Surface Chemistry
Music
General Relativity and Quantum Cosmology,
Discrete Mathematics and Combinatorics
General Veterinary
Agricultural and Biological Sciences (miscellaneous)
General Health Professions
Molecular Medicine
Engineering (miscellaneous)
Critical Care Nursing
Pediatrics
General Computer Science
Algebra and Number Theory
Multidisciplinary
Maternity and Midwifery
Emergency Nursing
Pharmacology, Toxicology and Pharmaceutics (miscellaneous)
Global and Planetary Change
Archeology
Electronic, Optical and Magnetic Materials
General Chemical Engineering
Audiology,
Orthodontics
Polymers and Plastics
Architecture
Geochemistry and Petrology
Analysis
Medical and Surgical Nursing
Hardware and Architecture
Health Information Management
Computational Theory and Mathematics
Optics and Photonics,
Hepatology
Allergy,
Sensory Systems
Dental Hygiene
Horticulture
Statistical and Nonlinear Physics
General Relativity and Gravitation,
General Nursing
General Agricultural and Biological Sciences
Optics,
Social Sciences,
Leadership and Management
General Decision Sciences
Paleontology
Pollution
Research and Theory
Emergency Medical Services
General Economics, Econometrics and Finance
Family Practice
Polymer Science,
General Business, Management and Accounting
Computational Chemistry,
General Relativity and Cosmology,
Probability and Uncertainty,
Earth-Surface Processes
Metals and Alloys
Speech and Hearing
Periodontics
Economics and Econometrics
Chemical Health and Safety
Aquaculture,
Computer-Aided Design,
Embryology
Nanomedicine,
Quantum Computing,
Synthetic Biology,
Systems Biology,
Instrumentation
Pharmacology (nursing)
Psychiatric Mental Health
Performing Arts,
Small Animals
Robotics and Automation,
General Arts and Humanities
Control and Optimization
Histology
Ethics,
Radiation
Health Psychology,
Psychology,
Strategy and Management
Forensic Medicine,
General Immunology and Microbiology
Veterinary,
Atomic and Molecular Physics,
Museology
Mechanics of Materials
Green chemistry,
Reliability,
Earth and Planetary Sciences
Forensic Science,
Environmental Science,
Dental Assisting
Experimental and Cognitive Psychology
Neurosciences,
Strategic and Management,
field_1_na
Mathematical Physics                     19
General Social Sciences                  18
Water Science and Technology             18
Literature and Literary Theory           17
Computational Biology,                   17
                                         ..
Environmental Science,                    1
Dental Assisting                          1
Experimental and Cognitive Psychology     1
Neurosciences,                            1
Strategic and Management,                 1
Name: count, Length: 133, dtype: int64